#Database setup
spring:
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none
  datasource:
    username: scottrbrtsn
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cognitive-health-toolshed?stringtype=unspecified
    password: postgres@123
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
  application:
    name: cognitive-health-toolshed
server:
  port: 9000

eureka:
  client:
    serviceUrl:
       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false